apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
    - name: hello-world
      #image: ramiro.azurecr.io/hello-webassembly:0.1
      image: gcr.io/ramiro-282822/hello-webassembly:0.2
      imagePullPolicy: Always
  imagePullSecrets:
    - name: regcred
  tolerations:
    - key: "krustlet/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoExecute"