[package]
name = "hello-world"
version = "0.1.0"
authors = ["Ramiro Berrelleza <rberrelleza@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wascc-actor = "0.7"
wascc-codec = "0.7"

[profile.release]
opt-level = "s"

[workspace]