apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2020-07-09T21:14:20Z"
  name: openfaas-operator-controller-profiles
rules:
- apiGroups:
  - openfaas.com
  resources:
  - profiles
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openfaas-operator-controller-profiles
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openfaas-operator-controller-profiles
subjects:
- kind: ServiceAccount
  name: openfaas-operator
  namespace: openfaas